[package]
name = "desktop-icons"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "desktop-icons"
path = "desktop-icons.rs"

[dependencies]
gtk = { version = "0.17", features = ["v3_24"] }
glib = "0.17"
gtk-layer-shell = "0.6"

